### PR TITLE
Update Forge / MCP Mappings. Boy, what a headache.

### PR DESCRIPTION
**Pull request by srs-bsns**
I dunno if anyone wants to go through to verify all this, because it would be quite tedious, But I did double-check all the mappings to make sure they're all correct. However, I did do a lot of "find and replace" at the directory level and there's a possibility of a few instances of local variables being changed from lowercase to uppercase. It won't break anything, but it just makes the code non-compliant with proper style.

in **src/main/java/teamrtg/rtg/world/gen/genlayer/GenLayerNoRivers.java**, I had to comment out **super.parent = par3GenLayer;** because access to that field in the super class is now **protected** with no means to set it. I didn't know how important that was, but considering the Forge devs don't want people touching it, I figured it's not.

This has been build tested, but not play tested.

###### (Edit: meant *protected* not *private*)

### CODE REVIEW

**Comment by srs-bsns** [comment]
So, I commented out **super.parent = par3GenLayer;** because IDEA was barking at me for accessing the super's protected field, so I had assumed something had changed, but it had not, and it still compiles and runs regardless. However, does this class even do anything @Zeno410? I couldn't figure it out at a glance, and after testing with it disabled I didn't notice anything different in the world.

I'm not too savvy with how this part of the mod works :smile: (Though I did clean up the code a bit.)

**Comment by Zeno410** [comment]
IIRC, that has to be set to prevent some other mod from crashing. If it's private, you have to set it with reflection.

**Comment by whichonespink44** [comment]
Just had a thought... we might be able to get away with leaving it commented out for now because the trouble mod probably hasn't updated to 1.9. Unless it was BOP?

**Comment by Zeno410** [comment]
No, it wasn't BoP. I can't remember what though.

**Comment by srs-bsns** [comment]
I don't think it needs to be commented out; The code is working fine as is. If it proves problematic, or if it the future it'ss deemed unneccessary, it can be removed then.

Unless anyone has an objection, this should be suitable for merging. It builds and runs fine without error.

**Comment by topisani** [comment]
You are right srs, you should have replaced `Blocks.dirt` instead of just `dirt`. This hasnt happened too many times though, so i think it should be alright

**Pull request merged**
