### PR TITLE
Update Forge, MCP mappings, deps.

### PR DESCRIPTION
**Pull request by srs-bsns**
***1 Upvote***

### CODE REVIEW

**Comment by whichonespink44** [comment]
Feel free to change to 'PR-Ready' if it's ok to merge.

**Comment by topisani** [comment]
i know im not supposed to do that, but it looks perfect, and i need that BOP version :dancer:

**Comment by whichonespink44** [comment]
Naughty Topi :stuck_out_tongue_winking_eye: 

@srs-bsns Is this cool to merge?

**Comment by srs-bsns** [comment]
Yeah, it's all good. Tested.

**Comment by whichonespink44** [comment]
:+1:

**Pull request merged**
