### PR TITLE
RTG 2.0 (or something)

### PR DESCRIPTION
**Pull request by topisani**
This PR is not supposed to be merged for now, its just to have a place to discuss things.
 - [ ] The entire config system is being rewritten
    - Take a look at the classes in `rtg.api.config`, specifically `Config`, `ConfigProperty` and `ModConfig`
 - [x] The biomes now define their surfaces and terrains in `initTerrain()` and `initSurface` instead of constructors.
 - [x] No more `Terrain` and `Surface` classes in seperate files for each biome.
 - [x] All mod support related stuff will be accessed from the `SupportedMods` enum.
    - This means we can do `SupportedMods.BOP.biomes.crag`
    - Config managers are gone. Its now `SupportedMods.BOP.getConfig()` and `SupportedMods.BOP.getConfig().getBiomeConfig(RealisticBiomeBOPCrag.class)`
    - And one of the perhaps best features: Other mods can now add 100% integration with RTG, adding biomes and whatnot, without us having to even know they exist. And all through a well documented API

### CODE REVIEW

**Comment by Zeno410** [comment]
Moving the terrain and surface inits out of the constructor calls will allow communication between them - you can pass the terrain to the surface so the surface can "query" the terrain for instructions.

SupportedMod as an enum is odd because you can add supported mods externally - but they're not in the enum.

**Comment by topisani** [comment]
Thats why its an Interface and not an enum, im just keeping them in an enum for easy Access to something like BOP.Present. but maybe you are right and constants are a better way to do it

**Comment by whichonespink44** [comment]
Is there an example of how a mod would go about adding their biome via the API? If not, can you describe (generally) how that would work? Are there any events that the mod would need to listen for?

**Comment by topisani** [comment]
I'll make a little example when it's done. Might be useful for the gitbook too

**Pull request merged**
