### PR TITLE
BiomegenBase biomes in RTG worlds

### PR DESCRIPTION
**Pull request by topisani**

### CODE REVIEW

**Comment by srs-bsns** [comment]
if all a3eed408a1aa8a4dfea6e9558ab6cd0712ea1943 does is "move classes around and create new packages" then why are there so many delete lines of code but nothing that gets added back? According to git it's all just deleted.

**Comment by topisani** [comment]
i have no idea srs, but it looks correct. I did delete all the surface classes for the supported mods, so that explains the 9000 lines

**Comment by whichonespink44** [comment]
@topisani Is this ready to be merged?

**Comment by topisani** [comment]
nah, keep it, im still working on it

**Comment by topisani** [comment]
this is at an allmost perfected state
just updating forge and BOP and testing with that and abyssalcraft

**Comment by Zeno410** [comment]
Are all the surfacing routines just boilerplate? There are certainly times it's deliberately different.

**Comment by topisani** [comment]
oh no, i meant i deleted them for all the mods i removed support for in v2. I had already removed the biomes i havent come around to updating, and in this i just removed the surfaces for those biomes (forgotten nature, BOP etc.)

**Comment by topisani** [comment]
Thats it i think!
Swamp is Realistic, the rest is BGB:

**Pull request merged**
