### PR TITLE
In theory added BOP support

### PR DESCRIPTION
**Pull request by topisani**
No way to test, since BOP still builds towards forge 1807. May do an RTG downgrade localy for testing purposes though.

This system uses the BOP biome layout if enabled and avaliable. Personally i think thats favourable to alternatives, any thoughts?

### CODE REVIEW

**Comment by topisani** [comment]
WOOHOO, confirmed working! BOP biomes in 1.9 :D

**Comment by whichonespink44** [comment]
Sweet! Is that using the 'local downgrade'?

**Comment by topisani** [comment]
nope apparently BOP jars works with 1809 but the source doesnt from the api folder. its all about #37

**Comment by topisani** [comment]
yep, latest commit made it all work. @srs-bsns i left a TODO item in build.gradle for you, could you check it out? its about #37 again

**Pull request merged**
