### PR TITLE
Fix SnowHeightCalculator.

### PR DESCRIPTION
**Pull request by topisani**
And lets try that again, shall we?
Fixes Team-RTG/1.9-Realistic-Terrain-Generation#18 and fixes Team-RTG/1.9-Realistic-Terrain-Generation#19

### CODE REVIEW

**Comment by whichonespink44** [comment]
Does this get rid of the checkerboard/grid thing as well?

**Comment by topisani** [comment]
yep, it was the same thing

**Comment by srs-bsns** [comment]
Is that the same checkerboard/grid thing that was noticed in 1.7.10 that hasn't been fixed yet?
Because this might give some insight on how to fix it there too.

**Comment by topisani** [comment]
nope, this one only fixes 1.9 update mistakes, it should look exactly like 1.7 currently

**Comment by whichonespink44** [comment]
> Is that the same checkerboard/grid thing that was noticed in 1.7.10 that hasn't been fixed yet?

I think #394 is a different issue, if that's the one you're referring to. I *still* haven't seen that one in all of my testing recently!

**Comment by whichonespink44** [comment]
Btw, I'm gonna merge this if that's cool with everyone.

**Comment by topisani** [comment]
merge ahead

**Pull request merged**
